version: '3.0'
services:
  mysql:
    container_name: social-network-user-servicee-mysql
    image: mysql:5.7
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql

volumes:
  mysql:
    driver: local