spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usersdb?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Dontbetoohumble1234!

socialnetwork:
  security:
    client:
      basicAuths:
        - {username: "social-network-usecase-service", password: "password", roles: ["role_admin", "role_user"]}