spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usersdb?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Dontbetoohumble1234!

socialnetwork:
  security:
    client:
      basicAuths:
        - {username: "social-network-usecase-service", password: "password", roles: ["USER"]}
        - {username: "back-office-usecase-service", password: "password", roles: ["ADMIN", "USER"]}
    endpointAuthorizations:
      - {urlPattern: "/api/v1/users/authorize", roles: ["ADMIN"]}
      - {urlPattern: "/api/v1/users/**", roles: ["USER", "ADMIN"]}